set_property SRC_FILE_INFO {cfile:C:/Users/rafat/OneDrive/Documents/FPGA/FPGA/projects/counter/counter/counter.srcs/constrs_1/new/blink_led.xdc rfile:../../../counter.srcs/constrs_1/new/blink_led.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports led]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk_in]
